/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 app/assets/3d/spotify_logo/scene.gltf 
Author: leesokleng (https://sketchfab.com/leesokleng)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotify-logo-090826d4a192443c89453cf256b9270e
Title: Spotify Logo
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function SpotifyLogo(props) {
  const groupRef = useRef();
  const shinyGreen = (
    <meshPhysicalMaterial
      color="#1DB954"
      metalness={0.3} // 0 = plastic, 1 = full metal
      roughness={0.1} // 0 = mirror, 1 = matte
      reflectivity={1}
      clearcoat={1} // glossy top coat layer
      clearcoatRoughness={0.05}
    />
  );

  const { nodes } = useGLTF("/3d/spotify_logo/scene.gltf");
  return (
    <group castShadow receiveShadow ref={groupRef} {...props} dispose={null}>
      <group scale={0.008}>
        <mesh castShadow receiveShadow geometry={nodes.Extrude_Mat_0.geometry}>
          {shinyGreen}
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Rounding_1_Mat_0.geometry}>
          {shinyGreen}
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Cap_1_Mat_0.geometry}>
          {shinyGreen}
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Rounding_2_Mat_0.geometry}>
          {shinyGreen}
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Cap_2_Mat_0.geometry}>
          {shinyGreen}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/3d/spotify_logo/scene.gltf");
